program Splendor;

uses
  Vcl.Forms,
  uPrincipal in 'uPrincipal.pas' {frmPrincipal},
  Vcl.Themes,
  Vcl.Styles,
  uDTMConexao in 'datamodule\uDTMConexao.pas' {dtmPrincipal: TDataModule},
  uTelaHeranca in 'heranca\uTelaHeranca.pas' {frmTelaheranca},
  uCadSetores in 'cadastro\uCadSetores.pas' {frmCadSetores},
  uEnum in 'heranca\uEnum.pas',
  cCadSetores in 'classes\cCadSetores.pas',
  uCadPessoa in 'cadastro\uCadPessoa.pas' {frmCadPessoa},
  cCadPessoa in 'classes\cCadPessoa.pas',
  untCongSistema in 'cadastro\untCongSistema.pas' {frmCongSistema},
  uCadIgreja in 'cadastro\uCadIgreja.pas' {frmCadIgreja},
  cCadIgreja in 'classes\cCadIgreja.pas',
  uFrmAtualizaDB in 'datamodule\uFrmAtualizaDB.pas' {frmAtualizaDB},
  uDTMTesouraria in 'datamodule\uDTMTesouraria.pas' {dtmTesouraria: TDataModule},
  uDTMRelatorio in 'datamodule\uDTMRelatorio.pas' {dtmRelatorio: TDataModule},
  uEmissaoDocumentos in 'Relatorios\uEmissaoDocumentos.pas' {frmEmitirDoc},
  uCadDepartamento in 'cadastro\uCadDepartamento.pas' {frmCadDepartamento},
  cCadDepartamento in 'classes\cCadDepartamento.pas',
  uCadCongregacao in 'cadastro\uCadCongregacao.pas' {frmCadCongregacao},
  cCadCongregacao in 'classes\cCadCongregacao.pas',
  uCadDizimo in 'cadastro\uCadDizimo.pas' {frmCadDizimos},
  cCadDizimo in 'classes\cCadDizimo.pas',
  uCadFuncao in 'cadastro\uCadFuncao.pas' {frmCadFuncao},
  cCadFuncao in 'classes\cCadFuncao.pas',
  uCadCargo in 'cadastro\uCadCargo.pas' {frmCadCargo},
  cCadUsuario in 'classes\cCadUsuario.pas',
  uCadDepartPessoa in 'cadastro\uCadDepartPessoa.pas' {frmCaddeparPessoa},
  cCadDepartPessoa in 'classes\cCadDepartPessoa.pas',
  uCadFuncaoPessoa in 'cadastro\uCadFuncaoPessoa.pas' {frmCadFuncaoPessoa},
  cCadFuncaoPessoa in 'classes\cCadFuncaoPessoa.pas',
  uFuncaoCriptografia in 'heranca\uFuncaoCriptografia.pas',
  cArquivoIni in 'classes\cArquivoIni.pas',
  uLogin in 'login\uLogin.pas' {frmLogin},
  uCadUsuario in 'cadastro\uCadUsuario.pas' {frmCadUsuario},
  cCadCargo in 'classes\cCadCargo.pas',
  Enter in 'terceiros\Enter.pas',
  uAlterarSenha in 'login\uAlterarSenha.pas' {frmAlterarSenha},
  cUsuarioLogado in 'classes\cUsuarioLogado.pas',
  uCadLancamento in 'cadastro\uCadLancamento.pas' {frmCadLancamento},
  cCadLancamento in 'classes\cCadLancamento.pas',
  cAtualizacaoBancoDeDados in 'classes\cAtualizacaoBancoDeDados.pas',
  cAtualizacaoTabelaMySQL in 'classes\cAtualizacaoTabelaMySQL.pas',
  uDepartamentos in 'Relatorios\uDepartamentos.pas' {frmRelDept},
  uCadCargoPessoa in 'cadastro\uCadCargoPessoa.pas' {frmCadCargoPessoa},
  cCadCargoPessoa in 'classes\cCadCargoPessoa.pas',
  cAtualizacaoCampoMySQL in 'classes\cAtualizacaoCampoMySQL.pas',
  cAcaoAcesso in 'classes\cAcaoAcesso.pas',
  uCadAcaoAcesso in 'cadastro\uCadAcaoAcesso.pas' {frmCadAcaoAcesso},
  uCadAjudaDeCusto in 'cadastro\uCadAjudaDeCusto.pas' {frmCadAjudaDeCusto},
  cCadRecibo in 'classes\cCadRecibo.pas',
  uUsuarioVsAcoes in 'login\uUsuarioVsAcoes.pas' {frmUsuarioVsAcoes},
  uConsultarDados in 'login\uConsultarDados.pas' {frmConsultaDados},
  uDTMGraficos in 'datamodule\uDTMGraficos.pas' {dtmGrafico: TDataModule},
  cCadProfessor in 'classes\cCadProfessor.pas',
  uCadProfessor in 'cadastro\uCadProfessor.pas' {frmCadProfessor},
  cCadClasse in 'classes\cCadClasse.pas',
  uCadClasse in 'cadastro\uCadClasse.pas' {frmCadClasse},
  cCadClasseAluno in 'classes\cCadClasseAluno.pas',
  uCadClasseAluno in 'cadastro\uCadClasseAluno.pas' {frmCadClasseAluno},
  uAniversariantes in 'Relatorios\uAniversariantes.pas' {frmAniversariantes},
  UEBD in 'Relatorios\UEBD.pas' {frmRelatoriosEBD},
  cFuncao in 'classes\cFuncao.pas',
  uTelaHerancaConsulta in 'heranca\uTelaHerancaConsulta.pas' {frmTelaHerancaConsulta},
  uBackupRestore in 'login\uBackupRestore.pas' {frmBackupRestore},
  cCadClasseProfessor in 'classes\cCadClasseProfessor.pas',
  uCadClasseProfessor in 'cadastro\uCadClasseProfessor.pas' {frmCadClasseProfessor},
  uImportarExportarDados in 'login\uImportarExportarDados.pas' {frmImportarExportarDados},
  uRelatoriosFinanceiro in 'Relatorios\uRelatoriosFinanceiro.pas' {frmRelatoriosFinanceiro},
  uDTMRelatorioFinanceiro in 'datamodule\uDTMRelatorioFinanceiro.pas' {dtmRelatorioFinanceiro: TDataModule},
  uQuadroAnual in 'Relatorios\uQuadroAnual.pas' {frmQuadroAnual},
  uChamadaEbd in 'ebd\uChamadaEbd.pas' {frmChamadaEbd},
  uDTMEbd in 'datamodule\uDTMEbd.pas' {dtmEbd: TDataModule},
  cCadEbdAula in 'ebd\cCadEbdAula.pas',
  uCadTipoCulto in 'cadastro\uCadTipoCulto.pas' {frmTipoCulto},
  cCadTipoCulto in 'classes\cCadTipoCulto.pas',
  cCadTipoSaida in 'classes\cCadTipoSaida.pas',
  uCadTipoSaida in 'cadastro\uCadTipoSaida.pas' {frmTipoSaida},
  uCadTipoCentroCusto in 'cadastro\uCadTipoCentroCusto.pas' {frmTipoCentroCusto},
  Entidade.TipoCentroCusto in 'entidade\Entidade.TipoCentroCusto.pas',
  uCadCentroCusto in 'cadastro\uCadCentroCusto.pas' {frmCadCentroCusto},
  Entidade.CentroCusto in 'entidade\Entidade.CentroCusto.pas',
  Entidade.Fornecedor in 'entidade\Entidade.Fornecedor.pas',
  uTelaHerancaEntidade in 'heranca\uTelaHerancaEntidade.pas' {frmTelaHerancaEntidade},
  uCadFornecedor in 'cadastro\uCadFornecedor.pas' {frmCadFornecedor},
  uCadLancUnificado in 'cadastro\uCadLancUnificado.pas' {frmCadLancUnificado},
  Entidade.TipoCulto in 'entidade\Entidade.TipoCulto.pas',
  Entidade.FormaPagamento in 'entidade\Entidade.FormaPagamento.pas',
  uCadFormpgto in 'cadastro\uCadFormpgto.pas' {frmCadFormpgto},
  Entidade.TipoLancamento in 'entidade\Entidade.TipoLancamento.pas',
  uCadTipoLancamento in 'cadastro\uCadTipoLancamento.pas' {frmCadTipoLancamento},
  Entidade.Tesouraria in 'entidade\Entidade.Tesouraria.pas',
  Entidade.TipoSaida in 'entidade\Entidade.TipoSaida.pas',
  Entidade.DespesaFixa in 'entidade\Entidade.DespesaFixa.pas',
  uCadDespesaFixa in 'cadastro\uCadDespesaFixa.pas' {frmCadDespesaFixa},
  uTUsuarioAcoesInThread in 'Thread\uTUsuarioAcoesInThread.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Amethyst Kamri');
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.Run;
end.
